# Pre-defined trainning deckes
class Deck:
    deck_list = []
    deck_list.append({"Class": 9,  # WARLOCK
                    "Deck": ["Soulfire",
                            "Soulfire",
                            "Abusive Sergeant",
                            "Abusive Sergeant",
                            "Argent Squire",
                            "Argent Squire",
                            "Flame Imp",
                            "Flame Imp",
                            "Leper Gnome",
                            "Leper Gnome",
                            "Mortal Coil",
                            "Mortal Coil",
                            "Voidwalker",
                            "Voidwalker",
                            "Young Priestess",
                            "Young Priestess",
                            "Dire Wolf Alpha",
                            "Dire Wolf Alpha",
                            "Knife Juggler",
                            "Knife Juggler",
                            "Harvest Golem",
                            "Harvest Golem",
                            "Shattered Sun Cleric",
                            "Shattered Sun Cleric",
                            "Dark Iron Dwarf",
                            "Dark Iron Dwarf",
                            "Defender of Argus",
                            "Defender of Argus",
                            "Doomguard",
                            "Doomguard",
                            ]})
    deck_list.append({"Class": 9,  # WARLOCK
                    "Deck": ["Soulfire",
                            "Soulfire",
                            "Mortal Coil",
                            "Mortal Coil",
                            "Ancient Watcher",
                            "Ancient Watcher",
                            "Ironbeak Owl",
                            "Ironbeak Owl",
                            "Sunfury Protector",
                            "Sunfury Protector",
                            "Earthen Ring Farseer",
                            "Earthen Ring Farseer",
                            "Defender of Argus",
                            "Defender of Argus",
                            "Hellfire",
                            "Hellfire",
                            "Shadowflame",
                            "Shadowflame",
                            "Twilight Drake",
                            "Twilight Drake",
                            "Faceless Manipulator",
                            "Faceless Manipulator",
                            "Siphon Soul",
                            "Sylvanas Windrunner",
                            "Ragnaros the Firelord",
                            "Lord Jaraxxus",
                            "Mountain Giant",
                            "Mountain Giant",
                            "Molten Giant",
                            "Molten Giant",
                            ]})
    deck_list.append({"Class": 9,  # WARLOCK
                    "Deck": ["Soulfire",
                            "Soulfire",
                            "Mortal Coil",
                            "Mortal Coil",
                            "Power Overwhelming",
                            "Power Overwhelming",
                            "Ancient Watcher",
                            "Ancient Watcher",
                            "Ironbeak Owl",
                            "Ironbeak Owl",
                            "Sunfury Protector",
                            "Sunfury Protector",
                            "Earthen Ring Farseer",
                            "Earthen Ring Farseer",
                            "Defender of Argus",
                            "Defender of Argus",
                            "Hellfire",
                            "Leeroy Jenkins",
                            "Shadowflame",
                            "Shadowflame",
                            "Twilight Drake",
                            "Twilight Drake",
                            "Faceless Manipulator",
                            "Faceless Manipulator",
                            "Sylvanas Windrunner",
                            "Ragnaros the Firelord",
                            "Mountain Giant",
                            "Mountain Giant",
                            "Molten Giant",
                            "Molten Giant",]})
    deck_list.append({"Class": 10,  # WARRIOR
                    "Deck": ["Execute",
                            "Execute",
                            "Shield Slam",
                            "Shield Slam",
                            "Whirlwind",
                            "Whirlwind",
                            "Armorsmith",
                            "Armorsmith",
                            "Cruel Taskmaster",
                            "Cruel Taskmaster",
                            "Fiery War Axe",
                            "Fiery War Axe",
                            "Slam",
                            "Acolyte of Pain",
                            "Acolyte of Pain",
                            "Big Game Hunter",
                            "Shield Block",
                            "Shield Block",
                            "Kor'kron Elite",
                            "Kor'kron Elite",
                            "Azure Drake",
                            "Brawl",
                            "Harrison Jones",
                            "Cairne Bloodhoof",
                            "Sylvanas Windrunner",
                            "Baron Geddon",
                            "Gorehowl",
                            "Grommash Hellscream",
                            "Ragnaros the Firelord",
                            "Alexstrasza"]})
    deck_list.append({"Class": 10,  # WARRIOR
                    "Deck": ["Argent Squire",
                             "Argent Squire",
                             "Leper Gnome",
                             "Leper Gnome",
                             "Southsea Deckhand",
                             "Southsea Deckhand",
                             "Upgrade!",
                             "Upgrade!",
                             "Bloodsail Raider",
                             "Bloodsail Raider",
                             "Faerie Dragon",
                             "Faerie Dragon",
                             "Fiery War Axe",
                             "Fiery War Axe",
                             "Heroic Strike",
                             "Heroic Strike",
                             "Frothing Berserker",
                             "Frothing Berserker",
                             "Harvest Golem",
                             "Harvest Golem",
                             "Arathi Weaponsmith",
                             "Dread Corsair",
                             "Dread Corsair",
                             "Kor'kron Elite",
                             "Kor'kron Elite",
                             "Leeroy Jenkins",
                             "Mortal Strike",
                             "Mortal Strike",
                             "Arcanite Reaper",
                             "Arcanite Reaper"]})
    deck_list.append({"Class": 7,  # ROGUE
                    "Deck": ["Shadowstep",
                            "Shadowstep",
                            "Argent Squire",
                            "Argent Squire",
                            "Cold Blood",
                            "Cold Blood",
                            "Deadly Poison",
                            "Deadly Poison",
                            "Leper Gnome",
                            "Leper Gnome",
                            "Southsea Deckhand",
                            "Southsea Deckhand",
                            "Defias Ringleader",
                            "Defias Ringleader",
                            "Eviscerate",
                            "Eviscerate",
                            "Loot Hoarder",
                            "Loot Hoarder",
                            "Sap",
                            "Sap",
                            "Arcane Golem",
                            "Arcane Golem",
                            "Coldlight Oracle",
                            "Coldlight Oracle",
                            "King Mukla",
                            "Edwin VanCleef",
                            "SI:7 Agent",
                            "SI:7 Agent",
                            "Leeroy Jenkins",
                            "Assassin's Blade"]})
    deck_list.append({"Class": 7,  # ROGUE
                    "Deck": ["Backstab",
                            "Backstab",
                            "Preparation",
                            "Preparation",
                            "Shadowstep",
                            "Shadowstep",
                            "Cold Blood",
                            "Cold Blood",
                            "Conceal",
                            "Conceal",
                            "Deadly Poison",
                            "Deadly Poison",
                            "Blade Flurry",
                            "Bloodmage Thalnos",
                            "Eviscerate",
                            "Eviscerate",
                            "Sap",
                            "Shiv",
                            "Shiv",
                            "Earthen Ring Farseer",
                            "Edwin VanCleef",
                            "Fan of Knives",
                            "Fan of Knives",
                            "SI:7 Agent",
                            "SI:7 Agent",
                            "Leeroy Jenkins",
                            "Azure Drake",
                            "Azure Drake",
                            "Gadgetzan Auctioneer",
                            "Gadgetzan Auctioneer",]})
    deck_list.append({"Class": 8,  # SHAMAN
                    "Deck": ["Argent Squire",
                            "Argent Squire",
                            "Earth Shock",
                            "Earth Shock",
                            "Leper Gnome",
                            "Leper Gnome",
                            "Lightning Bolt",
                            "Lightning Bolt",
                            "Rockbiter Weapon",
                            "Rockbiter Weapon",
                            "Bloodmage Thalnos",
                            "Flametongue Totem",
                            "Flametongue Totem",
                            "Knife Juggler",
                            "Knife Juggler",
                            "Loot Hoarder",
                            "Loot Hoarder",
                            "Windfury",
                            "Feral Spirit",
                            "Feral Spirit",
                            "Harvest Golem",
                            "Harvest Golem",
                            "Lava Burst",
                            "Lava Burst",
                            "Leeroy Jenkins",
                            "Azure Drake",
                            "Azure Drake",
                            "Doomhammer",
                            "Fire Elemental",
                            "Fire Elemental", ]})
    deck_list.append({"Class": 8,  # SHAMAN
                    "Deck": ["Argent Squire",
                            "Argent Squire",
                            "Earth Shock",
                            "Earth Shock",
                            "Lightning Bolt",
                            "Lightning Bolt",
                            "Rockbiter Weapon",
                            "Rockbiter Weapon",
                            "Bloodmage Thalnos",
                            "Flametongue Totem",
                            "Flametongue Totem",
                            "Feral Spirit",
                            "Feral Spirit",
                            "Hex",
                            "Hex",
                            "Lava Burst",
                            "Lava Burst",
                            "Lightning Storm",
                            "Lightning Storm",
                            "Mana Tide Totem",
                            "Mana Tide Totem",
                            "Defender of Argus",
                            "Sen'jin Shieldmasta",
                            "Sen'jin Shieldmasta",
                            "Azure Drake",
                            "Azure Drake",
                            "Doomhammer",
                            "Fire Elemental",
                            "Fire Elemental",
                            "Al'Akir the Windlord"]})
    deck_list.append({"Class": 5,  # PALADIN
                    "Deck": ["Abusive Sergeant",
                            "Abusive Sergeant",
                            "Argent Squire",
                            "Argent Squire",
                            "Blessing of Might",
                            "Blessing of Might",
                            "Elven Archer",
                            "Elven Archer",
                            "Leper Gnome",
                            "Leper Gnome",
                            "Worgen Infiltrator",
                            "Worgen Infiltrator",
                            "Argent Protector",
                            "Argent Protector",
                            "Equality",
                            "Equality",
                            "Knife Juggler",
                            "Knife Juggler",
                            "Divine Favor",
                            "Divine Favor",
                            "King Mukla",
                            "Consecration",
                            "Consecration",
                            "Hammer of Wrath",
                            "Hammer of Wrath",
                            "Leeroy Jenkins",
                            "Truesilver Champion",
                            "Truesilver Champion",
                            "Avenging Wrath",
                            "Avenging Wrath"]})
    deck_list.append({"Class": 5,  # PALADIN
                    "Deck": ["Elven Archer",
                            "Elven Archer",
                            "Humility",
                            "Equality",
                            "Equality",
                            "Wild Pyromancer",
                            "Wild Pyromancer",
                            "Aldor Peacekeeper",
                            "Aldor Peacekeeper",
                            "Earthen Ring Farseer",
                            "Earthen Ring Farseer",
                            "Consecration",
                            "Consecration",
                            "Hammer of Wrath",
                            "Hammer of Wrath",
                            "Sen'jin Shieldmasta",
                            "Sen'jin Shieldmasta",
                            "Truesilver Champion",
                            "Truesilver Champion",
                            "Azure Drake",
                            "Azure Drake",
                            "Stampeding Kodo",
                            "Stampeding Kodo",
                            "Sunwalker",
                            "Sunwalker",
                            "Guardian of Kings",
                            "Guardian of Kings",
                            "Lay on Hands",
                            "Lay on Hands",
                            "Tirion Fordring"]})
    deck_list.append({"Class": 3,  # HUNTER
                    "Deck": ["Abusive Sergeant",
                            "Abusive Sergeant",
                            "Arcane Shot",
                            "Arcane Shot",
                            "Argent Squire",
                            "Argent Squire",
                            "Leper Gnome",
                            "Leper Gnome",
                            "Deadly Shot",
                            "Deadly Shot",
                            "Worgen Infiltrator",
                            "Worgen Infiltrator",
                            "Explosive Trap",
                            "Explosive Trap",
                            "Knife Juggler",
                            "Knife Juggler",
                            "Misdirection",
                            "Misdirection",
                            "Animal Companion",
                            "Animal Companion",
                            "Arcane Golem",
                            "Arcane Golem",
                            "Eaglehorn Bow",
                            "Eaglehorn Bow",
                            "Kill Command",
                            "Kill Command",
                            "Unleash the Hounds",
                            "Unleash the Hounds",
                            "Wolfrider",
                            "Leeroy Jenkins"]})
    deck_list.append({"Class": 3,  # HUNTER
                    "Deck": ["Hunter's Mark",
                            "Hunter's Mark",
                            "Stonetusk Boar",
                            "Stonetusk Boar",
                            "Timber Wolf",
                            "Timber Wolf",
                            "Deadly Shot",
                            "Deadly Shot",
                            "River Crocolisk",
                            "River Crocolisk",
                            "Scavenging Hyena",
                            "Scavenging Hyena",
                            "Snake Trap",
                            "Snake Trap",
                            "Starving Buzzard",
                            "Starving Buzzard",
                            "Animal Companion",
                            "Animal Companion",
                            "Eaglehorn Bow",
                            "Eaglehorn Bow",
                            "Kill Command",
                            "Kill Command",
                            "Unleash the Hounds",
                            "Unleash the Hounds",
                            "Houndmaster",
                            "Houndmaster",
                            "Stranglethorn Tiger",
                            "Stranglethorn Tiger",
                            "Savannah Highmane",
                            "Savannah Highmane"]})
    deck_list.append({"Class": 4,  # MAGE
                    "Deck": ["Ice Lance",
                            "Ice Lance",
                            "Mirror Image",
                            "Bloodmage Thalnos",
                            "Doomsayer",
                            "Doomsayer",
                            "Frostbolt",
                            "Frostbolt",
                            "Loot Hoarder",
                            "Loot Hoarder",
                            "Novice Engineer",
                            "Acolyte of Pain",
                            "Acolyte of Pain",
                            "Arcane Intellect",
                            "Arcane Intellect",
                            "Frost Nova",
                            "Frost Nova",
                            "Ice Barrier",
                            "Ice Barrier",
                            "Ice Block",
                            "Ice Block",
                            "Fireball",
                            "Fireball",
                            "Blizzard",
                            "Blizzard",
                            "Archmage Antonidas",
                            "Flamestrike",
                            "Flamestrike",
                            "Alexstrasza",
                            "Pyroblast"]})
    deck_list.append({"Class": 4,  # MAGE
                    "Deck": ["Arcane Missiles",
                             "Arcane Missiles",
                             "Argent Squire",
                             "Argent Squire",
                            "Ice Lance",
                            "Ice Lance",
                            "Leper Gnome",
                            "Leper Gnome",
                            "Mana Wyrm",
                            "Mana Wyrm",
                            "Mirror Image",
                            "Mirror Image",
                            "Bloodmage Thalnos",
                            "Frostbolt",
                            "Frostbolt",
                            "Knife Juggler",
                            "Knife Juggler",
                            "Loot Hoarder",
                            "Loot Hoarder",
                            "Sorcerer's Apprentice",
                            "Sorcerer's Apprentice",
                            "Arcane Intellect",
                            "Arcane Intellect",
                            "Fireball",
                            "Fireball",
                            "Leeroy Jenkins",
                            "Water Elemental",
                            "Water Elemental",
                            "Azure Drake",
                            "Azure Drake"]})
    deck_list.append({"Class": 6,  # PRIEST
                    "Deck": ["Circle of Healing",
                            "Circle of Healing",
                            "Northshire Cleric",
                            "Northshire Cleric",
                            "Power Word: Shield",
                            "Power Word: Shield",
                            "Acidic Swamp Ooze",
                            "Shadow Word: Pain",
                            "Sunfury Protector",
                            "Wild Pyromancer",
                            "Earthen Ring Farseer",
                            "Injured Blademaster",
                            "Injured Blademaster",
                            "Shadow Word: Death",
                            "Shadow Word: Death",
                            "Thoughtsteal",
                            "Thoughtsteal",
                            "Auchenai Soulpriest",
                            "Auchenai Soulpriest",
                            "Sen'jin Shieldmasta",
                            "Sen'jin Shieldmasta",
                            "Shadow Madness",
                            "Faceless Manipulator",
                            "Holy Nova",
                            "Holy Nova",
                            "Cabal Shadow Priest",
                            "Holy Fire",
                            "Holy Fire",
                            "Sylvanas Windrunner",
                            "Ragnaros the Firelord"]})
    deck_list.append({"Class": 6,  # PRIEST
                    "Deck": ["Circle of Healing",
                            "Circle of Healing",
                            "Holy Smite",
                            "Holy Smite",
                            "Northshire Cleric",
                            "Northshire Cleric",
                            "Power Word: Shield",
                            "Power Word: Shield",
                            "Mind Blast",
                            "Mind Blast",
                            "Wild Pyromancer",
                            "Wild Pyromancer",
                            "Earthen Ring Farseer",
                            "Earthen Ring Farseer",
                            "Injured Blademaster",
                            "Injured Blademaster",
                            "Auchenai Soulpriest",
                            "Auchenai Soulpriest",
                            "Sen'jin Shieldmasta",
                            "Sen'jin Shieldmasta",
                            "Azure Drake",
                            "Azure Drake",
                            "Holy Nova",
                            "Holy Nova",
                            "Cabal Shadow Priest",
                            "Cabal Shadow Priest",
                            "Holy Fire",
                            "Holy Fire",
                            "Prophet Velen",
                            "Ragnaros the Firelord"]})
    deck_list.append({"Class": 2,  # DRUID
                      "Deck": ["Innervate",
                               "Innervate",
                               "Wild Growth",
                               "Wild Growth",
                               "Wrath",
                               "Wrath",
                               "Earthen Ring Farseer",
                               "Earthen Ring Farseer",
                               "Savage Roar",
                               "Savage Roar",
                               "Chillwind Yeti",
                               "Chillwind Yeti",
                               "Keeper of the Grove",
                               "Keeper of the Grove",
                               "Sen'jin Shieldmasta",
                               "Sen'jin Shieldmasta",
                               "Swipe",
                               "Swipe",
                               "Azure Drake",
                               "Azure Drake",
                               "Druid of the Claw",
                               "Druid of the Claw",
                               "Cairne Bloodhoof",
                               "Force of Nature",
                               "Force of Nature",
                               "Sylvanas Windrunner",
                               "Ancient of Lore",
                               "Ancient of Lore",
                               "Ancient of War",
                               "Ancient of War",]})
    deck_list.append({"Class": 2,  # DRUID
                      "Deck": ["Innervate",
                               "Innervate",
                               "Argent Squire",
                               "Argent Squire",
                               "Bloodmage Thalnos",
                               "Loot Hoarder",
                               "Loot Hoarder",
                               "Power of the Wild",
                               "Power of the Wild",
                               "Wrath",
                               "Wrath",
                               "Big Game Hunter",
                               "Harvest Golem",
                               "Harvest Golem",
                               "Savage Roar",
                               "Savage Roar",
                               "Keeper of the Grove",
                               "Keeper of the Grove",
                               "Swipe",
                               "Swipe",
                               "Violet Teacher",
                               "Violet Teacher",
                               "Azure Drake",
                               "Azure Drake",
                               "Druid of the Claw",
                               "Druid of the Claw",
                               "Force of Nature",
                               "Force of Nature",
                               "Ancient of Lore",
                               "Ancient of Lore",]})
    deck_list.append({"Class": 2,  # DRUID
                        "Deck": ["Innervate",
                                "Innervate",
                                "Bloodmage Thalnos",
                                "Power of the Wild",
                                "Power of the Wild",
                                "Wild Growth",
                                "Wild Growth",
                                "Wrath",
                                "Wrath",
                                "Harvest Golem",
                                "Harvest Golem",
                                "Savage Roar",
                                "Savage Roar",
                                "Keeper of the Grove",
                                "Keeper of the Grove",
                                "Leeroy Jenkins",
                                "Swipe",
                                "Swipe",
                                "Violet Teacher",
                                "Violet Teacher",
                                "Azure Drake",
                                "Azure Drake",
                                "Druid of the Claw",
                                "Druid of the Claw",
                                "Force of Nature",
                                "Force of Nature",
                                "Ancient of Lore",
                                "Ancient of Lore",
                                "Ancient of War",
                                "Cenarius"]})
